### PR TITLE
Add Avell A60 MUV as lightbar_supported

### PR DESCRIPTION
**Pull request by ArlindoFNeto**
I've suggested this in #89 issue.

### CODE REVIEW

**Comment by tuxedoxt** [comment]
Hello,

sorry for the delay.

You are correct, for those devices we aim to include general support. As far as I can tell, yes, this should be safe to include.

**Comment by tuxedoxt** [comment]
Do you know if there is a separate device name for LAPQC71B?

**Comment by ArlindoFNeto** [comment]
Hello tuxedoxt,

Thanks for the informations about the code and the merge.

Until now, the Avell company sell only the LAPQ71A as model AV60 MUV. There is no models of LAPQ71{B,C,D} to sell by Avell company.

**Comment by tuxedo-wse** [comment]
@ArlindoFNeto Hi,
temporary unarchiving this repo.
We are relicensing tuxedo-drivers to GPLv2+.
As far as I can tell this commit would count as a trivial change because no real logic is included/there is pretty much only this way to do this.
But nontheless I would like to ask you if you you are ok with GPLv2+ for this commit?

**Comment by tuxedo-wse** [comment]
Also do you have a contact e-mail? The commit only has a dummy mail adress.

**Comment by ArlindoFNeto** [comment]
> @ArlindoFNeto Hi, temporary unarchiving this repo. We are relicensing tuxedo-drivers to GPLv2+. As far as I can tell this commit would count as a trivial change because no real logic is included/there is pretty much only this way to do this. But nontheless I would like to ask you if you you are ok with GPLv2+ for this commit?

Yes! I agree with GPLv2+!

**Comment by ArlindoFNeto** [comment]
> Also do you have a contact e-mail? The commit only has a dummy mail adress.

arlindo@lopan.eti.br

**Comment by tuxedo-wse** [comment]
thanks 👍

**Pull request merged**
