### PR TITLE
Relicensing from GPLv3 to GPLv2+

### LINKED ISSUE #61: Licensing incompatibility between Linux kernel and these kernel modules
I was looking into this project's kernel modules to figure out packaging it, and I discovered that this project's license is not compatible with the Linux kernel's own license, thus the combination is not redistributable.

The Linux kernel is GPLv2 (SPDX: `GPL-2.0-only`), and the kernel modules are GPLv3+ (SPDX: `GPL-3.0-or-later`). As GPLv3 is incompatible with GPLv2 when the combination of software cannot be upgraded to GPLv3 on redistribution (as is the case with the Linux kernel), shipping this or getting this merged into the mainline kernel will not be possible without fixing the licensing of these modules first.

Please can you relicense the modules to GPLv2+ (SPDX: `GPL-2.0-or-later`) to make it compatible with the Linux kernel?

I suspect this was an unintentional incompatibility, and I hope this can be swiftly resolved.

### PR DESCRIPTION
**Pull request by vinzv**
To fix #61 we need to relicense tuxedo-keyboard from GPLv3 to GPLv2+.

Asking external contributors (as in people not working for TUXEDO): @ashh87 @Brainiarc7 and @pointhi - any objections against the relicensing from you?

### CODE REVIEW

**Comment by pointhi** [comment]
I agree the re-licensing from GPLv3 to GPLv2+

**Comment by Conan-Kudo** [comment]
@vinzv Don't forget that all license headers need to be updated.

**Comment by Conan-Kudo** [comment]
I would also recommend that the commit message be amended to have `Signed-off-by` statements to represent all contributing parties, similar to what I did for relicensing microdnf: https://github.com/rpm-software-management/microdnf/commit/31df71c946efc49fe54d158729b9aa06ce45d3a5

**Review by ckristi — APPROVED** [review]
I believe this would be a definite step forward, as the module won't taint the kernel anymore. Moreover, I would really love to see this module merged into mainline kernel.

**Comment by ruzko** [comment]
What tasks remain before this pull request can be merged?

**Comment by brunoais** [comment]
> What tasks remain before this pull request can be merged?

Answers from @ashh87 & @Brainiarc7 .

**Comment by ashh87** [comment]
I also agree to the relicensing - thought I had commented on this ages ago.

**Comment by brunoais** [comment]
@vinzv Do you think we should still be waiting for @Brainiarc7? Most of his contributions don't seem to be substantial enough to copyright. It's very welcome changes to README and changes to configuration files.

**Comment by stefan-niedermann** [comment]
I just wrote @Brainiarc7 a mail asking for approving those changes. Hopefully we can get this stuff upstream as soon as possible :rocket:

**Comment by Brainiarc7** [comment]
Please proceed to re-license from GPLv3 to GPLv2+, as it's needed for merging upstream.
Thank you.

**Comment by stefan-niedermann** [comment]
Awesome! Thank you!

@vinzv how shall we proceed? I guess rebasing this branch and merging it into master are the next steps?

**Comment by Conan-Kudo** [comment]
Well, you also need to fix all the file headers and record the signoffs in the commit. The current commit message is not sufficient for that record.

**Comment by leonardozz** [comment]
@vinzv I created [7f6c7f9](https://github.com/leonardozz/tuxedo-keyboard/commit/7f6c7f98c137b10dff29fe2c3e0f185c19a5d47c) to sort out what @Conan-Kudo mentioned about the license headers.

Hopefully the only missing part to move forward with this would be to add the `Signed-off-by` statements to the commit message.

Thanks in advance to everyone whom contributed to this and looking forward to having this into the mainline Linux Kernel.

**Comment by jondo** [comment]
Who needs to add these `Signed-off-by` statements?

**Comment by stefan-niedermann** [comment]
➡️ Little rant (sorry for that).

So this is some kind of ridiculous. Since **four** years, people (*including* the original authors) want to relicense this stuff to match the Kernel license. (#17, #61, #108 ...)

Not only that *noone* contradicted, no. Everyone *explicitly* aggreed!
Pull Requests are *ready*, still there seems to be no progress. What are you waiting for? People who contributed a new line in the `README` half a decade ago and explicitly stated to finally relicense the module. A few more years and noone will respond to our requests anymore.

People do have issues with various distributions, new concepts arrive (like immutable operating systems) that make it even harder to use this driver.

Even I as an open source fan can not understand, *what exactly* is needed to get this done.

So please: Add a clear description (bullet points) **who** has to do **what** exactly. I will happily run around and get the contributors together, ask everyone to do what needs to be done.

This "non-communication" is a pity.

**Comment by Brainiarc7** [comment]
What task is pending on this PR? All contributors (to my knowledge) have
already agreed to the re-locensing.

**Comment by vincentdephily** [comment]
> What task is pending on this PR? 

At least changing the license headers in source files (this PR only changes the main LICENSE file). For example [clevo_acpi.c](https://github.com/tuxedocomputers/tuxedo-keyboard/blob/master/src/clevo_acpi.c) has a GPLv3 header.

It's probably wise to follow the kernel's [license rules docs](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/process/license-rules.rst?h=v6.2.11) to make upstreaming easy. I suggest using a SPDX identifier instead of license text.

**Comment by vincentdephily** [comment]
Ah sorry, I hadn't seen @leonardozz 's PR which does change the file headers, although not using SPDX.

Speaking of which, I don't want to slow the process down but I wonder why `GPL-2.0+` was chosen instead of `GPL-2.0` ? AFAIK the `or-later` variant works, but if we're relicensing to match the kernel we might as well match it exactly by using the `only` variant ?

**Comment by Conan-Kudo** [comment]
There is no requirement to be `GPL-2.0-only`. Plenty of sources in Linux are `GPL-2.0-or-later`: https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Ftorvalds%2Flinux%24+GPL-2.0-or-later&patternType=standard&sm=1&groupBy=path

**Comment by jondo** [comment]
It seems this  waiting leads to nothing. Would it help if I created an SPDX version of the PR?

Can someone from Tuxedo please confirm that [all necessary contributors have agreed](https://github.com/tuxedocomputers/tuxedo-keyboard/pull/62#issuecomment-1484096651)?

CCing @tuxedoxt, the active contributor, and the recent contributor @Matombo from https://github.com/tuxedocomputers.

**Comment by salim-b** [comment]
> Speaking of which, I don't want to slow the process down but I wonder why `GPL-2.0+` was chosen instead of `GPL-2.0` ? AFAIK the `or-later` variant works, but if we're relicensing to match the kernel we might as well match it exactly by using the `only` variant ?

To keep tuxedo-keyboard's code compatible with software licensed under `GPL-3.0-or-later`. Even the [GPL authors strongly advise to use the `-or-later` license versions](https://www.gnu.org/licenses/identify-licenses-clearly.html) in order to avoid further situations like this very issue.

**Comment by salim-b** [comment]
See https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers/-/issues/137 for a follow-up issue.

**Pull request closed without merging**
